name: Build a Docker image
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build a docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: /Dockerfile
          push: false

